eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  data:
    redis:
      url: ${REDIS_PROD_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 0.1
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces